export const dataModel = [
    {
        name: 'name',
        label: '姓名',
        col: 12,
        rules: [{
            required: true,
            message: '请输入人员姓名',
            trigger: 'blur'
        }]
    }, {
        name: 'password',
        label: '系统密码',
        col: 12,
        rules: [{
            required: true,
            message: '请输入系统密码',
            trigger: 'blur'
        }, {
            min: 6,
            message: '系统密码最少6位',
            trigger: 'blur'
        }]
    }, {
        name: 'dePartName',
        label: '部门名称',
        type: 'select',
        rules: [{
            required: true,
            message: '请选择部门名称',
            trigger: ['change', 'blur']
        }],
        col: 12,
        options: []
    }, {
        name: 'jobName',
        label: '职位名称',
        type: 'select',
        rules: [{
            required: true,
            message: '请输入职位名称',
            trigger: ['change', 'blur']
        }],
        col: 12,
        options: []
    }, {
        name: 'idcard',
        col: 12,
        label: '身份证号',
        rules: [{
            required: true,
            message: '请输入人员身份证号码',
            trigger: 'blur'
        }]
    }, {
        name: 'tel',
        col: 12,
        label: '手机号',
        rules: [{
            required: true,
            message: '请输入人员手机号码',
            trigger: 'blur'
        }]
    }, {
        name: 'phone',
        col: 12,
        label: '分机号',
    }, {
        name: 'wagesCardNo',
        col: 12,
        label: '工资卡号',
    }, {
        name: 'email',
        col: 12,
        label: '电子邮箱',
    }, {
        name: 'qq',
        col: 12,
        label: '工作QQ',
    }, {
        name: 'joindate',
        col: 12,
        label: '入职日期',
    }, {
        name: 'sex',
        col: 12,
        label: '性别',
        type: 'radio',
        defaultValue: '保密',
        options: [{
            label: '女'
        }, {
            label: '男'
        }, {
            label: '保密'
        }]
    }, {
        name: 'birthday',
        col: 12,
        label: '出生日期'
    }, {
        name: 'marriage',
        label: '婚姻状况',
        type: 'select',
        col: 12,
        options: [{
            label: '已婚'
        }, {
            label: '未婚'
        }]
    }, {
        name: 'face',
        label: '政治面貌',
        type: 'select',
        col: 12,
        options: [{
            label: '群众'
        }, {
            label: '团员'
        }, {
            label: '党员'
        }]
    }, {
        name: 'nation',
        col: 12,
        label: '民族',
    }, {
        name: 'nativePlace',
        col: 12,
        label: '籍贯',
    }, {
        name: 'eduSchool',
        col: 12,
        label: '毕业院校',
    }, {
        name: 'edu',
        col: 12,
        label: '学历',
    }, {
        name: 'major',
        col: 12,
        label: '专业',
    }, {
        name: 'personHeight',
        col: 12,
        label: '身高',
    }, {
        name: 'personWeight',
        col: 12,
        label: '体重',
    }, {
        name: 'contractStartDate',
        type: 'date',
        col: 12,
        label: '合同起始日',
    }, {
        name: 'contractEndDate',
        type: 'date',
        col: 12,
        label: '合同截止日',
    }
]